version: '3'
services:
  web:
    container_name: amit-delfina-web
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./app:/code/app"
    environment:
      UNSPLASH_CLIENT_ID: ${UNSPLASH_CLIENT_ID}
      UNSPLASH_API_URL: ${UNSPLASH_API_URL}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
